language: elixir
elixir:
  - 1.7.10
otp_release:
  - '20.0'
addons:
  postgresql: '9.4'
  mysql: '5.6'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

env:
  global:
    - MIX_ENV=test

before_script:
  - mix test.reset
script:
  - mix compile --all-warnings --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
